### PR TITLE
Request header fixes and error logging

### PR DESCRIPTION
**Pull request by tsnowlan**
Two separate header fixes:
1. Uploads from MultiQC to MegaQC with nginx as a proxy are currently failing. This is because MultiQC uses `api_token` as the header, and the strict header spec does not allow underscores. MultiQC should probably change that, but until then it's a good idea to have the nginx container allow underscores in header names.
2. CSRF protection was also left on for the new `/rest_api` routes, but CSRF tokens aren't in use in the web forms POSTing to `/rest_api` causing them to fail. Disabled to match the prior settings on the old `/api` routes.

Also modified the error handler to send json when responding to `/rest_api` and log what errors were received on the flask side as well. Helpful for when an error message is being swallowed somewhere.

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Not allowing the full UTF-8 charset is one thing, but not allowing underscores?? 🤦🏻 

Easy enough to change upstream in MultiQC. Is it worth adding the code here to accept both `api_token` and `apitoken` so that an upstream fix won't break stuff here?

Phil

**Comment by TMiguelT** [comment]
The changes look good, although check the pre-commit hooks. I think fixing the proxy in the short term will be easier than fixing the token header itself. 

As always, I would certainly appreciate a test for this. I already have a `docker-compose` stack test (which is in the build script, it should really be in Python), and adding an upload call to that would make for a nice test.

**Comment by tsnowlan** [comment]
I think if anything, changing the multiqc side to be `api-token` instead of `api_token` is probably the simplest. Flask/werkzeug turns `-` in headers into `_` in the variable names, so it shouldn't need any changes in MegaQC to accommodate.

Tests are good. I'll check out the docker-compose stack and add some.

**Comment by TMiguelT** [comment]
> Flask/werkzeug turns - in headers into _ in the variable names, so it shouldn't need any changes in MegaQC to accommodate.

Oh, I didn't know this. That makes it a little easier, but I think I would still have to edit a lot of tests that use the header as-is

**Comment by tsnowlan** [comment]
@TMiguelT added upload tests both via nginx proxy and directly to gunicorn/flask. Also added a sleep before and `--fail` to the `curl localhost` test, as I saw that it had actually been returning 500 since the db wasn't up and going yet and the test was still passing.

For the upload test, I added `./test:/opt/test` as a volume on the megaqc and db services instead of doing `docker cp` to the specific containers in the build test. It seemed a bit cleaner. A side effect is these directories will also be mounted for anyone just testing things out. Shouldn't be an issue I don't think?

**Comment by TMiguelT** [comment]
Note to self to update the black config so that this diff gets cleaner (currently it's including some black changes).

I know this is getting picky, and I'm sorry to ask for more changes, but do you think you could move the tests into Python? I know I started the stack tests in the build script but I realise now that was a mistake.

I think the easiest way to do this would be make a new pytest test, and in it you spin up the stack using say subprocess (running `docker-compose`), ideally create the data using API calls and not an SQL script, and then run the assertions *outside* the docker stack, still from pytest. That way we get easy pytest integration in a single language, and we've tested the whole stack end-to-end from outside, which is how it will ultimately be used. 

I'm happy if you do the same logic as you have where you test the proxy and also directly test the flask endpoint, but ideally in Python. I think you could do this by using the host networking stack when you create the stack maybe? Unfortunately I'm not a big fan of adding a new volume to the production stack just for testing.

**Comment by TMiguelT** [comment]
@tsnowlan can you grant me edit permission for this PR? I assume you haven't because:

```bash
git push ousamg fix-csrf-headers 
ERROR: Permission to ousamg/MegaQC.git denied to TMiguelT.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tsnowlan** [comment]
Just sent you an invite to that repo, though I see now you've got another PR going. I'll have a few more PRs in coming days, so might still be useful

**Comment by TMiguelT** [comment]
Great! Although actually I meant this button:

**Comment by ewels** [comment]
I imagine that @TMiguelT was referring to this checkbox: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

But not everyone always has that checkbox available, depending on how your user account / organisation / forked repo is set up.

**Comment by ewels** [comment]
This feature for GitHub is absolutely amazing as a maintainer by the way - I use it on MultiQC PR reviewing all the time. Means I can make minor changes and push to the PR before merging, makes it super clear what was done and keeps the discussion in one place 🚀

**Comment by tsnowlan** [comment]
Ah, that is very cool! I don't have that option available though, I'm guessing because it's an org owned as opposed to one owned by me.

**Comment by TMiguelT** [comment]
Ah, that makes sense.

**Comment by TMiguelT** [comment]
I'm going to merge my branch into yours, and then into master if that's okay, @tsnowlan. It will keep everything in one neat place.

**Comment by tsnowlan** [comment]
Sounds good to me

**Pull request merged**
