### PR TITLE
Create github actions workflows

### LINKED ISSUE #100: Use GitHub actions
Might be nice to switch to GitHub actions instead of Travis for CI, once everything is merged. Low priority.

### LINKED ISSUE #106: Providing pre-built JavaScript
As per earlier discussion, we now have a build process for compiling the JavaScript, which adds an additional hurdle for people wanting to install MegaQC.

We could either:
* Keep it as is, meaning users now have to install `node` to compile the JS
* Add the compiled JS to source control
* Include pre-compiled JS to MegaQC *releases*

I prefer this latter approach because adding the compiled JS to source will muddy up the diffs, add redundancy, and increase the repo size. As it stands, this would be a manual release process, but later on we could add a release mechanism whereby we tag a commit, then the CI compiles the JS, makes a release, and attaches a zip file with the compiled JS to that release.

Oh, and we can also include this compiled JS in the pip package, which can also be automatically released using the CI. 

Thoughts?

### PR DESCRIPTION
**Pull request by TMiguelT**
* Port CI from Travis to GitHub Actions
* Create build script that publishes PyPI packages and GitHub releases with compiled JavaScript when a release is tagged

Closes #100, closes #106.

### CODE REVIEW

**Comment by TMiguelT** [comment]
I'm not super happy about duplicating all the steps from the other workflows into `.github/workflows/release.yaml`, but the other alternative is chucking both JS and Python logic into one giant workflow that also conditionally runs the deploy step. I don't like that because then the build matrix can't run in parallel anymore.

**Comment by TMiguelT** [comment]
Oh, would you mind generating a PyPI API token that has push access to `megaqc` and then adding it to GitHub actions as `PYPI_PASSWORD`, @ewels?

[Docs are here](https://pypi.org/help/#apitoken).

**Comment by TMiguelT** [comment]
@ewels any chance of this happening?

**Comment by ewels** [comment]
Done 👍

**Comment by ewels** [comment]
This is super cool by the way! Nice work! ✅

**Comment by TMiguelT** [comment]
Great! And do you mind if I make a new release with this? `0.2` I'm thinking.

**Comment by TMiguelT** [comment]
Actually, I should fix some small issues with my changes before I release. Namely #105, #114, #116 and #111.

**Pull request merged**
