### PR TITLE
User registration improvements

### PR DESCRIPTION
**Pull request by TMiguelT**
https://github.com/ewels/MegaQC/blob/1941ad65c38baf4c34bb895e68e1442fac1ed015/docs/changelog.md#L3-L25

### CODE REVIEW

**Comment by ewels** [comment]
Wait, to _disable_ the user confirmation step you set `STRICT_REGISTRATION` to _true_? That seems backwards..

**Comment by ewels** [comment]
Why not set `USER_REGISTRATION_APPROVAL: false` in the config yaml?

**Comment by TMiguelT** [comment]
Oh oops, it's like that because initially strict was opt-in, but now it's opt-out.

**Comment by TMiguelT** [comment]
Okay, I think I'm happy with this. Feel free to review.

**Pull request merged**
