### PR TITLE
React implementation of control/trend charts

### PR DESCRIPTION
**Pull request by TMiguelT**
I've settled on React as the only reasonable option for rewriting the frontend in a readable and modular way.

## Features

- Rewrote the entirety of the `/trends` page in React, including the filter select box, the new filter modal, and the trend plots
image

- UI looks almost identical before, due to the use of bootstrap components ([reactstrap](https://reactstrap.github.io/))
- The code is much more readable, modular and declarative now!
- Added a JSON API client, which talks really nicely with the #87 REST API
- Trend plots now include a mean and standard deviation by default!
image
- Added a useful outlier detection feature. This lets you choose a detection method (currently Grubbs test or Z-score), and it will highlight outliers in red. For example, with a Z-score threshold of 2 standard deviations: 
image

## Installation
In addition to the regular MegaQC installation, you will also have to install NodeJS, and then run:
```bash
# Install JS dependencies
npm install
# Compile JS
webpack
```
Then open the website at the trends page

## Note
This PR forks off the #87 REST API branch, so once that is merged, this diff becomes a lot simpler! This PR should basically change none of the Python code, and only introduce some JavaScript.

### CODE REVIEW

**Comment by TMiguelT** [comment]
Updated with new features, and make this into a full PR!

**Comment by TMiguelT** [comment]
Updated to fix the issue discussed in https://github.com/ewels/MegaQC/issues/48#issuecomment-568343359

**Comment by TMiguelT** [comment]
* [ ] Check favourite plots not working

**Comment by TMiguelT** [comment]
@ewels, just so you know, I've fixed the plot favourites stuff, but I did so in the admin PR, because of structural changes in that PR. So you'll only need to actually merge that one.

**Comment by ewels** [comment]
Ah crap sorry, I only just read this message _after_ I just merged the JSON api PR. I'll see if I can revert the merge.

**Comment by TMiguelT** [comment]
No it's fine actually. Both this and `admin` are based on `generic-api`. I'm just advising against merging *this* PR. But merging `generic-api` and then `admin` is fine.

**Comment by ewels** [comment]
ok, in that case I will undo the undo and re-merge the `generic-api` branch. I think I got merge conflicts on `admin` after that, but we can handle them there..

**Comment by TMiguelT** [comment]
Agreed. I suspect any conflicts are from my changes to `generic-api` that I haven't merged back into `admin`. I'll do that now.

**Pull request merged**
