### PR TITLE
Remove pagination from find() calls

### PR DESCRIPTION
**Pull request by TMiguelT**
**PR Checklist**

- [x] This comment contains a description of changes (with reason)
- [x] Referenced issue is linked
- [ ] ~~If you've fixed a bug or added code that should be tested, add tests!~~
- [ ] ~~Documentation in `docs` is updated~~
- [x] `docs/changelog.md` is updated

**Description of changes**

Explicitly disable pagination for `find()` calls, ensuring we get more than 30 results in certain places. Described in #148.

**Technical details**

This is kind of a bad solution because it requires us to specify 0 pages each time we make a request. Some other options we have are:
* Forking the client to add default query params
* Editing the backend's default pagination threshold and increasing it from 30

### CODE REVIEW

**Comment by TMiguelT** [comment]
This is just waiting on me to complete #196 so that I can test that this works.

**Comment by TMiguelT** [comment]
I've informally "tested" that this fixes the 30-field limit issue, but there aren't formal tests in place.

**Review by Zethson — APPROVED** [review]
I don't have an idea for a better solution.
LGTM

**Review by tsnowlan — APPROVED** [review]
looks good to me

**Pull request merged**
